name: mobile_pos
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  #Get
  get:
  get_storage:
  #IMAGE
  lottie:
  cached_network_image:
  pin_code_fields:
  #API
  dio:
  retrofit:
  freezed_annotation:
  json_serializable:
  json_annotation: ^4.6.0
  #ENV
  flutter_dotenv: ^5.0.2
  #DATABASE
  hive:
  hive_flutter:
  #ICON
  material_design_icons_flutter:
  #OTHER
  flutter_svg:
  google_fonts:
  logging:
  logger:
  url_launcher:
  dotted_border:
  flutter_shapes:
  fl_chart: ^0.55.2
  numeric_keyboard: ^1.1.0
  grouped_list:
  flutter_image_compress:
  image_picker:
  wechat_assets_picker: ^8.1.1
  permission_handler: ^10.1.0
  app_settings: ^4.1.8
  path_provider:
  collection:
  dotted_line: ^3.1.0
  qr_flutter: ^4.0.0
  screenshot: ^1.2.3
  open_file: ^3.2.1
  share_plus:
  #KEYBOARD SHOW/OFF
  flutter_keyboard_visibility:
  #CALENDAR
  syncfusion_flutter_datepicker: ^20.2.36
  intl: ^0.17.0

  ai_barcode_scanner: ^0.0.3
  just_audio: ^0.9.13
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.1.3
  freezed: 2.1.0+1
  build_runner:
  hive_generator:
  retrofit_generator:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  flavors:
    prod:
      app:
        name: "YHS Multi POS"
      android:
        applicationId: "com.sm.yhsmultipos"
      ios:
        bundleId: "com.sm.yhsmultipos"
    dev:
      app:
        name: "YHS Multi POS Dev"
      android:
        applicationId: "com.sm.yhsmultipos.dev"
      ios:
        bundleId: "com.sm.yhsmultipos.dev"

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/logos/
    - assets/lotties/
    - assets/svg/
    - assets/sound/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyPOSIcons
      fonts:
        - asset: assets/fonts/MyPOS.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
