/// Flutter icons MyPOS
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyPOS
///      fonts:
///       - asset: fonts/MyPOS.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyPOSIcons {
  MyPOSIcons._();

  static const _kFontFam = 'MyPOSIcons';
  static const String? _kFontPkg = null;

  static const IconData chartbar =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chartpie =
      IconData(0xf200, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chartline =
      IconData(0xf201, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxes =
      IconData(0xf468, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxopen =
      IconData(0xf49e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weighthanging =
      IconData(0xf5cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
